#!/bin/bash
# ─────────────────────────────────────────────
# SharkShell — Docker Compose Init Script
# Generates secrets before first run
# ─────────────────────────────────────────────
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SECRETS_DIR="${SCRIPT_DIR}/.secrets"
ENV_FILE="${SCRIPT_DIR}/.env"

echo ""
echo "  🦈 SharkShell Docker Setup"
echo "  ─────────────────────────"
echo ""

mkdir -p "$SECRETS_DIR"

# ── Generate .env if missing ──
if [ ! -f "$ENV_FILE" ]; then
    echo "📝 Creating .env from .env.example..."

    # Generate strong DB password
    DB_PASS=$(openssl rand -base64 24 | tr -d '\n/+=')
    ENCRYPTION_KEY=$(openssl rand -hex 32)

    cat > "$ENV_FILE" <<EOF
# ─── SharkShell Docker Config ───
# Auto-generated by init.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# ── Database (internal PostgreSQL) ──
DB_HOST=postgres
DB_PORT=5432
DB_USER=sharkshell
DB_PASSWORD=${DB_PASS}
DB_NAME=sharkshell

# ── External Database (uncomment to use your own) ──
# DB_EXTERNAL=true
# DB_HOST=your-db-host.com
# DB_PORT=5432
# DB_USER=your_user
# DB_PASSWORD=your_password
# DB_NAME=your_database

# ── Security ──
ENCRYPTION_KEY=${ENCRYPTION_KEY}
# JWT uses auto-generated RSA key files (more secure than string secrets)
# If you want to use a simple string instead, uncomment:
# JWT_SECRET=your-secret-here

# ── App ──
PORT=3002
COMPOSE_PORT=8080
EOF

    echo "   ✅ .env created with auto-generated credentials"
    echo "   ⚠️  Review and customize ${ENV_FILE} before deploying"
else
    echo "   ✅ .env already exists, skipping generation"
fi

echo ""
echo "  Ready! Run:"
echo "    docker compose up --build -d"
echo ""
